# Generated by Django 4.2.24 on 2025-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizationrequest',
            name='visualization_type',
            field=models.CharField(choices=[('timeline', 'Timeline'), ('character_map', 'Character Relationship Map'), ('plot_diagram', 'Plot Structure Diagram'), ('mood_chart', 'Mood/Tone Chart'), ('word_cloud', 'Word Cloud'), ('flowchart', 'Mermaid Flowchart')], max_length=20),
        ),
    ]
